{% set name = "fluidsim-core" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 72d214084c6c8a50563908a3109227fa25a34f395162ba08acb61b06ff150731

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - fluiddyn >=0.3.2

test:
  imports:
    - fluidsim_core
    - fluidsim_core.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://foss.heptapod.net/fluiddyn/fluidsim
  summary: Pure-Python core library for FluidSim framework
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
