{% set name = "fluidsim-core" %}
{% set version = "0.9.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7a025a2c55e27432a91e4b40aa5cddaa183d4c6d1087b44d6b3a6750195f6425

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - fluiddyn >=0.3.2

test:
  imports:
    - fluidsim_core
    - fluidsim_core.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://foss.heptapod.net/fluiddyn/fluidsim
  summary: Pure-Python core library for FluidSim framework
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
